% ******** Introduction: ********
%
% This script performs simulations of acoustic pressure fields emanating
% from an acoustic point source.The pressure fields generated by the
% acoustic source pioint were computed by using function
% comp_press_field_point_source. The resulting pressure against time was
% also plotted in this script. Mathermatically, the pressure field is given
% by p(x,y,z,t) = p_0 * (¦Ä(t-r/c)/4 * pi *r),
% where r = sqrt((x-x0)^2 + (y-y0)^2 + (z-z0)^2). We can call the above
% equation, Equation (1).

% ******** Clear Space: ********

% Starts timing
tic;

% Clear all contents from command window
clc;

% Clear all variables from workspace
clear;

% Close all figures
close all;

% ******** Parameters: ********

% Pressure field at acoustic pressure source point(x0,y0,z0) = (0,0,0)mm,
% hence define (x0, y0, z0) position in unit of m
x0 = 0;

y0 = 0;

z0 = 0;

x_s = x0;

y_s = y0;

z_s = z0;

% To compute the pressure field at grid point(x,y,z) = (1,1,0)mm
% So define (x, y, z) position in unit of m
xcoors = 1 * 0.001;

ycoors = 1 * 0.001;

zcoors = 0;

x = xcoors;

y = ycoors;

z = zcoors;

% Define the total number of steps along x,y and z direction
Numx = length(xcoors);

Numy = length(ycoors);

Numz = length(zcoors);

% We use sound speed c = 1500 m/s to simulate water or soft biological
%tissue
c = 1500;

% We use the initial pressure amplitude p_0 = 1 Pa¡¤m
p_0 = 1;

% Pressure varys as a function of time, and the time range is
% 0<= t <= 3¦Ìs with a temporal step size ¦¤t = 10 ns.
% So define time t in unit of seconds

dt = 1.0000e-08;

upper_t = 3.0000e-06;

lower_t = 0;

t = lower_t:dt:upper_t;

Numt = length(t);

% The time we want to terminate is at the upper time limit,  3¦Ìs in this
% case
t_end = upper_t;

% Find the index where the time equals to the time the user wants to
% terminate.
inx = find(t == t_end);

% ******** Methods: ********

% Compute the pressure value and return the time axis
[pressure,t]  = comp_press_field_point_source(x,x_s,y,y_s,z,z_s,p_0,c,upper_t,lower_t,dt,t_end,inx);


% ******** Results: ********

% Plot the resulting pressure against time in miliseconds
plot(t*1e06,squeeze(pressure(1,1,1,:))');

% label the x-axis
xlabel('Time [us]');

% label the y-axis
ylabel('Pressure [Pa]');

% giving a title on the figure
title('Pressure as function of time for an acoustic point source');


% ******** Error checking and finish timing: ********

% Indicate the error if there is one
dbstop if error;

% Finish timing and display the time spent for running this code
fprintf('The total running time of Task1_script is: %.6f seconds. \n',toc');


